//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace meeeh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lamp
    {
        public int ID_L { get; set; }
        public Nullable<int> Voltage { get; set; }
        public int ID_P { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
